trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DeleteFiles@1
  displayName: 'Delete node cache and git files'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
     .git/*
     node_modules/*
     client/node_modules/*
    RemoveSourceFolder: true

- task: ArchiveFiles@2
  displayName: 'Create Deployment Archive'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

- task: AzureWebApp@1
  displayName: 'Azure Web App Deploy: solutions'
  inputs:
    azureSubscription: 'Invoice to Interactive Services Directly (5e202bcb-f2cb-4b49-a7e8-0d1987d60e08)'
    appType: 'webAppLinux'
    appName: 'solutions'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    runtimeStack: 'NODE|10-lts'
    startUpCommand: 'npm start run'